# Generated by Django 5.1.2 on 2024-11-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
